version: "3"

services:
  app:
    build: .
    container_name: tereamsk.ru # меняем на имя проекта
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tereamsk.ru, www.tereamsk.ru
      - LETSENCRYPT_HOST=tereamsk.ru, www.tereamsk.ru
      - LETSENCRYPT_EMAIL=qwe@gmail.com
      - REDIRECT_www.tereamsk.ru=tereamsk.ru
    networks:
      - web
    volumes:
      # Все сайты используют одну и ту же папку с картинками
      - /var/www/iluma-store.ru/images:/app/public/images:ro
      # - /var/www/tereamsk.ru/.next:/app/.next

networks:
  web:
    external: true
